### ISSUE TITLE
Add ids to ui elements

### ISSUE THREAD

**Issue by claytonneal** [vechain/vechain-dapp-kit#220]
for tools like cypress/playwright could be good to add some id's to the modal wallet options
for example to click on VeWorld is currently like:

`await page.locator('div.modal-body button.card.LIGHT').first().click();`

i.e. relying on it being "first"

**Comment by darrenvechain** [comment]
This won't work since we're using lit elements. It creates nested shadow roots that are not directly queryable (see screenshot)

Might be better to describe the requirement rather than the implementation, eg. make it easy for devs to interact with UI elements

<img width="1195" alt="image" src="https://github.com/vechain/vechain-dapp-kit/assets/107671032/14d11cec-5ad4-4c32-9e12-a95d4759035b">

**Comment by claytonneal** [comment]
Playwright can query such elements
im currently using playwright to click on that element, works fine
see: https://playwright.dev/docs/locators#locate-in-shadow-dom

**Comment by davidecarpini** [comment]
@claytonneal this playwright feature is amazing, it's such a pita to work with selenium and nested shadow dom.
I'll add them for you in the next days

**Comment by claytonneal** [comment]
see PR : https://github.com/vechain/vechain-dapp-kit/pull/238
